<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-Deputy.Cli-7ebf71cc-d04e-4f19-a8ac-9ac3ee3610e6</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Graffs" Version="0.1.0" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.11" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Deputy.Tests" />
  </ItemGroup>
</Project>
